# Generated by Django 3.2.6 on 2022-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projecttable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='summery',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
