# Generated by Django 3.2.6 on 2022-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projecttable_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttable',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projecttable',
            name='max_depth',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projecttable',
            name='number_of_bore_home',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
