# Generated by Django 3.2.6 on 2022-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221116_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttable',
            name='ags_file',
            field=models.FileField(blank=True, null=True, upload_to='project/ags/'),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='project/thumnails/'),
        ),
    ]
