# Generated by Django 3.2.6 on 2022-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221116_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='max_depth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
