# Generated by Django 3.2.6 on 2022-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221116_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='number_of_bore_home',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
