# Generated by Django 3.2.6 on 2022-11-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_projecttable_number_of_bore_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttable',
            name='ags_file',
        ),
        migrations.CreateModel(
            name='ProjectAGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ags_file', models.FileField(blank=True, null=True, upload_to='project/ags/')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.projecttable')),
            ],
        ),
    ]
