# Generated by Django 3.2.6 on 2022-11-21 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221116_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectags',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectags',
            name='ags_file',
            field=models.FileField(blank=True, null=True, upload_to='project/ags/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ags'])]),
        ),
        migrations.AlterField(
            model_name='projectags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projecttable'),
        ),
    ]
