# Generated by Django 3.2.6 on 2022-12-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contacttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
