# Generated by Django 3.2.6 on 2023-02-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_projectdefaultprofilecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectdefaultprofile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable1', models.CharField(max_length=200)),
                ('variable2', models.CharField(max_length=200)),
                ('variable3', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projecttable')),
            ],
        ),
    ]
