# Generated by Django 3.2.6 on 2023-02-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_projectdefaultprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdefaultprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projectdefaultprofilecategory'),
        ),
    ]
