# Generated by Django 3.2.6 on 2023-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230225_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectags',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectexcel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
