# Generated by Django 3.2.6 on 2023-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_projectdefaultprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdefaultprofile',
            name='chartindex',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
