# Generated by Django 3.2.6 on 2023-02-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_projectdefaultprofile_chartindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdefaultprofile',
            name='chartindex',
        ),
    ]
