# Generated by Django 3.2.6 on 2023-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_projectdefaultprofile_chartindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
