# Generated by Django 3.2.6 on 2023-03-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230225_1424'),
        ('home', '0018_projectprofile_is_default'),
    ]

    operations = [
    ]
