# Generated by Django 3.2.6 on 2023-04-02 03:28

import apps.home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_projectags_fractionangle_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectags',
            name='ags_file',
            field=models.FileField(upload_to=apps.home.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ags'])]),
        ),
    ]
